version: '3'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          memory: '512M'

  scraping-script:
    build:
      context: .
      dockerfile: Dockerfile.scraping-script
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/
    deploy:
      resources:
        limits:
          cpus: '0.5'

volumes:
  mongodb_data:
